name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - name: Install rustfmt
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Run rustfmt
      run: cargo fmt --all

    - name: Build
      run: cargo build --verbose
    
    - name: Run Tests
      run: cargo test --verbose

    - name: Generate Code Docs
      run: cargo doc --no-deps --verbose
